const participants = [
    {
        id: 1,
        name: 'Виктор',
        position: 'Командир',
        image: 'avatar.png',
        icon: 'commandir.svg',
        birthdate: '03.07.2003',
        days: 30,
        sex: 'Мужской',
        verify: true,
        payed: true,
        inSquad: true,
        useIcon: true,
        confidant: [],
    },
    {
        id: 2,
        name: 'Александр',
        position: 'Коммисар',
        image: 'avatar.png',
        icon: 'commisar.svg',
        birthdate: '06.07.2005',
        days: 21,
        sex: 'Мужской',
        verify: true,
        payed: true,
        inSquad: true,
        useIcon: true,
        confidant: [],
    },
    {
        id: 3,
        name: 'Екатерина',
        position: 'Мастер',
        image: 'avatar.png',
        icon: 'master.svg',
        birthdate: '13.11.2001',
        days: 22,
        sex: 'Женский',
        verify: true,
        payed: true,
        inSquad: true,
        useIcon: true,
        confidant: [],
    },
    {
        id: 4,
        name: 'Александр',
        position: 'Медик',
        image: 'avatar.png',
        icon: 'medic.svg',
        birthdate: '11.12.2002',
        days: 25,
        sex: 'Мужской',
        verify: true,
        payed: true,
        inSquad: true,
        useIcon: true,
        confidant: [],
    },
    {
        id: 5,
        name: 'Виктор',
        position: 'Боец',
        image: 'avatar.png',
        birthdate: '03.07.2003',
        days: 15,
        sex: 'Мужской',
        verify: true,
        payed: true,
        inSquad: true,
        useIcon: false,
        confidant: [],
    },
    {
        id: 6,
        name: 'Виктор',
        position: 'Боец',
        image: 'avatar.png',
        birthdate: '03.07.2003',
        days: 15,
        sex: 'Мужской',
        verify: true,
        payed: true,
        inSquad: true,
        useIcon: false,
        confidant: [],
    },
    {
        id: 7,
        name: 'Виктор',
        position: 'Боец',
        image: 'avatar.png',
        birthdate: '03.07.2003',
        days: 15,
        sex: 'Мужской',
        verify: true,
        payed: true,
        inSquad: true,
        useIcon: false,
        confidant: [],
    },
    {
        id: 8,
        name: 'Виктор',
        position: 'Командир',
        image: 'avatar.png',
        birthdate: '03.07.2003',
        days: 15,
        sex: 'Мужской',
        verify: false,
        payed: true,
        inSquad: true,
        useIcon: false,
        confidant: [],
    },
    {
        id: 9,
        name: 'Виктор',
        position: 'Боец',
        image: 'avatar.png',
        birthdate: '03.07.2003',
        days: 15,
        sex: 'Мужской',
        verify: true,
        payed: true,
        inSquad: true,
        useIcon: false,
        confidant: [],
    },
    {
        id: 10,
        name: 'Виктор',
        position: 'Боец',
        image: 'avatar.png',
        birthdate: '03.07.2003',
        days: 15,
        sex: 'Мужской',
        verify: false,
        payed: false,
        inSquad: true,
        useIcon: false,
        confidant: [],
    },
    {
        id: 11,
        name: 'Виктор',
        position: 'Боец',
        image: 'avatar.png',
        birthdate: '03.07.2003',
        days: 15,
        sex: 'Мужской',
        verify: true,
        payed: false,
        inSquad: true,
        useIcon: false,
        confidant: [],
    },
    {
        id: 12,
        name: 'Виктор',
        position: 'Боец',
        image: 'avatar.png',
        birthdate: '03.07.2003',
        days: 15,
        sex: 'Мужской',
        verify: true,
        payed: true,
        inSquad: true,
        useIcon: false,
        confidant: [],
    },
    {
        id: 13,
        name: 'Виктор',
        position: 'Боец',
        image: 'avatar.png',
        birthdate: '03.07.2003',
        days: 15,
        sex: 'Мужской',
        verify: true,
        payed: false,
        inSquad: true,
        useIcon: false,
        confidant: [],
    },
    {
        id: 14,
        name: 'Виктор',
        position: 'Боец',
        image: 'avatar.png',
        birthdate: '03.07.2003',
        days: 15,
        sex: 'Мужской',
        verify: false,
        payed: true,
        inSquad: true,
        useIcon: false,
        confidant: [],
    },
    {
        id: 15,
        name: 'Виктор',
        position: 'Боец',
        image: 'avatar.png',
        birthdate: '03.07.2003',
        days: 15,
        sex: 'Мужской',
        verify: false,
        payed: true,
        inSquad: true,
        useIcon: false,
        confidant: [],
    },
    {
        id: 16,
        name: 'Виктор',
        position: 'Боец',
        image: 'avatar.png',
        birthdate: '03.07.2003',
        days: 15,
        sex: 'Мужской',
        verify: true,
        payed: true,
        inSquad: true,
        useIcon: false,
        confidant: [],
    },
    {
        id: 17,
        name: 'Виктор',
        position: 'Боец',
        image: 'avatar.png',
        birthdate: '03.07.2003',
        days: 15,
        sex: 'Мужской',
        verify: false,
        payed: true,
        inSquad: true,
        useIcon: false,
        confidant: [],
    },
    {
        id: 18,
        name: 'Виктор',
        position: 'Боец',
        image: 'avatar.png',
        birthdate: '03.07.2003',
        days: 15,
        sex: 'Мужской',
        verify: false,
        payed: true,
        inSquad: true,
        useIcon: false,
        confidant: [],
    },
    {
        id: 19,
        name: 'Алекс',
        position: 'Боец',
        image: 'avatar.png',
        birthdate: '03.07.2003',
        days: 0,
        sex: 'Мужской',
        verify: true,
        payed: true,
        inSquad: false,
        useIcon: false,
        confidant: [],
    },
    {
        id: 20,
        name: 'Степан',
        position: 'Боец',
        image: 'avatar.png',
        birthdate: '03.07.2003',
        days: 0,
        sex: 'Мужской',
        verify: true,
        payed: true,
        inSquad: false,
        useIcon: false,
        confidant: [],
    },
    {
        id: 21,
        name: 'Алла',
        position: 'Боец',
        image: 'avatar.png',
        birthdate: '03.07.2003',
        days: 0,
        sex: 'Женский',
        verify: true,
        payed: true,
        inSquad: false,
        useIcon: false,
        confidant: [],
    },
];

export default participants;
