export enum UserRole {
    CENTRAL_HEADQUARTER_COMMANDER,
    DISTRICT_HEADQUARTER_COMMANDER,
    REGIONAL_HEADQUARTER_COMMANDER,
    LOCAL_HEADQUARTER_COMMANDER,
    EDUCATIONAL_HEADQUARTER_COMMANDER,
    DETACHMENT_COMMANDER,
}
