const participants = [
    {
        id: 1,
        name: 'Виктор',
        position: 'Командир',
        image: 'avatar.png',
        icon: 'commandir.svg',
        birthdate: '03.07.2003',
        days: 30,
        inSquad: true,
        useIcon: true,
    },
    {
        id: 2,
        name: 'Александр',
        position: 'Коммисар',
        image: 'avatar.png',
        icon: 'commisar.svg',
        birthdate: '06.07.2005',
        days: 21,
        inSquad: true,
        useIcon: true,
    },
    {
        id: 3,
        name: 'Екатерина',
        position: 'Мастер',
        image: 'avatar.png',
        icon: 'master.svg',
        birthdate: '13.11.2001',
        days: 22,
        inSquad: true,
        useIcon: true,
    },
    {
        id: 4,
        name: 'Николай',
        position: 'Коммисар',
        image: 'avatar.png',
        icon: 'commisar.svg',
        birthdate: '06.07.2005',
        days: 21,
        inSquad: true,
        useIcon: true,
    },
];

export default participants;
