export {default as FirstPanel} from './FirstPanel.vue';
export {default as FourthPanel} from './FourthPanel.vue';
export {default as FifthPanel} from './FifthPanel.vue';
export {default as SixthPanel} from './SixthPanel.vue';
export {default as SeventhPanel} from './SeventhPanel.vue';
export {default as NinthPanel} from './NinthPanel.vue';
export {default as TenthPanel} from './TenthPanel.vue';
export {default as EleventhPanel} from './EleventhPanel.vue';
export {default as TwelfthPanel} from './TwelfthPanel.vue';
export {default as ThirteenthPanel} from './ThirteenthPanel.vue';
export {default as SixteenthPanel} from './SixteenthPanel.vue';
export {default as SeventeenthPanel} from './SeventeenthPanel.vue';
export {default as EighteenthPanel} from './EighteenthPanel.vue';
export {default as NineteenthPanel} from './NineteenthPanel.vue';
export { default as CalculatedPanel } from './CalculatedPanel.vue';