import Input from './Input.vue';
import TextArea from './textarea.vue';
import Search from './search.vue';
import passwordInput from './passwordInput.vue';
import InputReport from './InputReport.vue';
import TextareaReport from './TextareaReport.vue';
import TextareaAbout from './TextareaAbout.vue';
import headSelect from './headSelect.vue';
import ErrorMessage from './ErrorMessage.vue';
import DatePicker from './DatePicker.vue';
export { Input, TextArea, Search, TextareaAbout, headSelect, passwordInput, InputReport, TextareaReport, ErrorMessage, DatePicker };
